version: "3"

services:
  p3db:
    image: mariadb
    restart: always
    container_name: project3_db
    ports:
      - "33060:3306"
    # expose:
    #   - "8765" 
    volumes:
      - ./databases/data:/var/lib/mysql
      # - ./databases/mariadbcnf.d:/etc/mysql/conf.d
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: project3
      MYSQL_DATABASE: project3
      MYSQL_USER: admin
      MYSQL_PASSWORD: project3
    networks:
      - default 
      - p3_net
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=project3 --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 60s
      retries: 10


  p3api: &python
    depends_on:
      p3db:
        condition: service_healthy
    tty: true
    image: django
    restart: always
    container_name: project3_api
    build:
      context: ./jaruda_back
    command: >
      bash -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"  
    networks:
      - default 
      - p3_net
    ports:
      - "8000:8000"
    # expose:
    #   - "8000" 


  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - "15672"
  celery_worker:
    <<: *python
    container_name: project3_api_celery_worker
    command: celery -A jaruda_back worker --loglevel=info
    ports: []
    depends_on:
      - rabbitmq
      - p3db
  celery_beat:
    <<: *python
    container_name: project3_api_celery_beat
    command: celery -A jaruda_back beat --loglevel=info
    ports: []
    depends_on:
      - rabbitmq
      - p3db
  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
#      - CELERY_BROKER_URL=amqp://rabbitmq
      - FLOWER_PORT=5555
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq
      - celery_worker
      - celery_beat


networks:
  p3_net:
    driver: bridge