# Generated by Django 4.0.4 on 2022-05-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=70)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
